name: 'Azure Visum'
descriprion: 'deletar a s branchs abertas com task em done'
author: 'Marcus Vinicius'

inputs:
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: true
  TENOR_TOKEN:
    description: 'Tenor API token'
    required: true

runs:
  using: 'node20'
  main: 'dist/index.js'